[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = '0.8.20'
evm_version = "paris"

[profile.ci]
fuzz_runs = 100000
solc = "./lib/v4-core/bin/solc-static-linux"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
